### ISSUE TITLE
No Wifi on T460s 

### ISSUE THREAD

**Issue by Ezak91** [nicogig/T460s-Clover#1]
Hey,

i have an T460s and i used your EFI to install Catalina OS.
But i cant get wlan work.

First i had an DW1830 but no Wifi Symbol nothing.
Then i buy your card the DW1820A now i have an wlan symbol but cant activate wlan 
Maybe wrong cable connection?

Can you help me?

Thank you and best regards

**Comment by nicogig** [comment]
Hi,
unfortunately it’s a bit hard to say but we can try to fix that. What’s the part number of your card? Have you checked that it is compatible with OS X?

**Comment by luodonglai** [comment]
IMO, maybe it is more with catalina? I have DW1560 and it works in Mojave.

**Comment by Ezak91** [comment]
@nicogig 

the part number is CN-0VW3T3 and it should be compatible.
Can you make a picture how you connect your card? and whats your bios version

thank you for your help

**Comment by Ezak91** [comment]
I get my D1830 running by delete the properties for the dw1820a, that was all...
I think the device properties for my dw1820a are not the same as yours (part number)
